theme: jekyll-theme-minimal
title: Python College Analytics
description: >
  <h2>College Data Analysis using basic python commandst</h2>
  <p>
    <b>LinkedIn:</b> <a href="https://www.linkedin.com/in/sindujasivasailam" target="_blank"> Sinduja S</a> 
    <br>
    <br>
    <b>Libraries:</b>
    <ul>
      <li>Pandas</li>
      <li>DataFrame</li>
    </ul>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  </p>
---
